Add video link
DPI-WE/join-the-chat pull request #6
Opened 2024-10-24 16:19 UTC by heratyian

closes #5

2024-10-24 16:57 UTC, aldoportillo requested changes
## Please Fix or Advice on
Why are we using `<aside>` tag? 

I'm under the impression that most if not all markdown renderers won't format markdown inside html tags.

If we want to use this aside tag we might need `[How to Use Discord](https://youtu.be/z5c6Bc-S0TI)` to be changed to `<a href="https://youtu.be/z5c6Bc-S0TI">How to Use Discord</a>`.

## Evidence

<img width="530" alt="Screenshot 2024-10-24 at 11 59 18 AM" src="https://github.com/user-attachments/assets/c4e9ba73-4149-4172-8885-fdf200ac7099">
Inside markdown preview in VSCode

<img width="1049" alt="Screenshot 2024-10-24 at 12 02 20 PM" src="https://github.com/user-attachments/assets/09322ef7-90bf-4663-9d30-0b1526d71a80">
Inside Github

2024-10-25 14:33 UTC, heratyian commented
> Why are we using `<aside>` tag?

It's used in Learn to create a side section to provide more context. We could move this inline if you think it's important for everyone to watch.

![image](https://github.com/user-attachments/assets/7b61437a-3ce2-4f6a-8196-e779f578d15a)

2024-10-25 16:50 UTC, aldoportillo approved these changes

2024-10-25 16:51 UTC, aldoportillo commented
Looks great!

2024-10-25 16:52 UTC, merged